#----------------------------------------------------------------------------------------------------------------------------------------
#SERVER
---
server:
  port: 8010

spring:
  profiles:
    active: default
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#logging:
#  level:
#    com:
#      netflix:
#        discovery: OFF
#        eureka: OFF
#timeout
#  server:
#    wait-time-in-ms-when-sync-empty: 0

#---
#spring:
#    profiles: primary
#server:
#  port: 8011
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8012/eureka/,http://localhost:8013/eureka/

#---
#spring:
#    profiles: secondary
#server:
#  port: 8012
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8013/eureka/,http://localhost:8011/eureka/

#---
#spring:
#    profiles: tertiary
#server:
#  port: 8013
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/

#----------------------------------------------------------------------------------------------------------------------------------------
#LOG
#%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN: -%5p} %m%n
#%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n
#Default
#%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
#----------------------------------------------------------------------------------------------------------------------------------------
#TODO

